### ISSUE TITLE
Lottie.framework/Lottie' (no such file)

### ISSUE THREAD

**Issue by soulsoft** [millionscard/react-native-knotapi#11]
Hello, 

After installing and Autolinking the library, the app builds successfully and I'm getting a black screen, on the log it shows this error message  
'/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.5.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/Lottie.framework/Lottie' (no such file),
'/usr/lib/swift/Lottie.framework/Lottie' (no such file),

Additional infos : 
React-native: 0.68.2.
react-native-knotapi: lastest 0.1.33

**Comment by soulsoft** [comment]
Hi, i've upgraded the react-native-knotapi package to version 0.1.39, it doesn't work i've got this error message on logs,

`[!] CocoaPods could not find compatible versions for pod "KnotAPI":
  In snapshot (Podfile.lock):
    KnotAPI (= 0.1.41, ~> 0.1.41)

  In Podfile:
    react-native-knotapi (from `../node_modules/react-native-knotapi`) was resolved to 0.1.39, which depends on
      KnotAPI (~> 0.1.44)

Specs satisfying the `KnotAPI (= 0.1.41, ~> 0.1.41), KnotAPI (~> 0.1.44)` dependency were found, but they required a higher minimum deployment target.`

but it worked after changing s.dependency 'KnotAPI', '~> 0.1.44' to s.dependency 'KnotAPI', '~> 0.1.41'  on react-native-knotapi.podspec .

**Comment by kieranoreilly** [comment]
Hi if you can run this command and let me know if it solves the problem.
```
 pod update KnotAPI
```
